"""Initial migration - create blog and user tables

Revision ID: ad207aecabb0
Revises: d7b0073b1d5f
Create Date: 2025-07-20 18:41:31.927334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad207aecabb0'
down_revision: Union[str, None] = 'd7b0073b1d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
